tasks:
  - command: >
        bash -i .devcontainer/install.sh
    
vscode:
  extensions:
    - tintinweb.graphviz-interactive-preview
    - cssho.vscode-svgviewer
    - tomoki1207.pdf
    - efanzh.graphviz-preview
    - mhutchie.git-graph
